# Generated by Django 4.0.1 on 2022-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_model', models.IntegerField()),
                ('std_shift_time', models.IntegerField()),
                ('total_break_time_gross', models.IntegerField()),
                ('start_up', models.IntegerField()),
                ('t_break', models.IntegerField()),
                ('lunch', models.IntegerField()),
                ('others', models.IntegerField()),
                ('std_shift_time_net', models.IntegerField()),
                ('days_or_week', models.IntegerField()),
                ('week_or_year', models.IntegerField()),
            ],
        ),
    ]
